base_url = "https://devendrn.github.io/newb-shader/"
compile_sass = true
build_search_index = false

title = "AziFy-Shaders"
description = "AziFy Shaders has many varieties but all of them focused on making Minecraft Better!"
author = "devendrn"

theme = "devnzt"

[markdown]
highlight_code = true

[extra]
error404_title = "Error 404"
error404_description = "Bro Has a Low Internet... 💀"

header_links = [
    { name = "Download", url = "download" },
    { name = "Help", url = "help" },
]

footer_content = "Copyright &copy; Azi Angelo &ensp;|&ensp; This site is not associated with Mojang or Microsoft."
